name: Changelog
description: Parses changelog milestones
inputs:
  token:
    description: Github token
    required: true
  pull_requests:
    description: |
      Pull requests JSON Array. Required fields: number, url, milestone, title, body, state.
    required: true
  allowed_sections:
    description: |
      Sections config for the validation of possible values. Optional. Accepts comma-separated or newline-sepatated strings.
      Forced impact_level can be added with a colon. Example:

        chrony
        ci:low
        docs
        node-manager
    required: false
outputs:
  yaml:
    description: Changelog YAML
  markdown:
    description: Changelog markdown
runs:
  using: "node12"
  main: "dist/index.js"
