name: Changelog
description: Parses changelog milestones
inputs:
  token:
    description: Github token
    required: true
  pull_requests:
    description: |
      Pull requests JSON Array. Required fields: number, url, milestone, title, body, state.
    required: true
outputs:
  yaml:
    description: Changelog YAML
  markdown:
    description: Changelog markdown
runs:
  using: "node12"
  main: "dist/index.js"
