name: Changelog
description: Parses changelog milestones
inputs:
  token:
    description: Github token
    required: true
  pull_requests:
    description: |
      Pull requests JSON

      Required fields: number, url, milestone, title, state
    required: true
outputs:
  body:
    description: Changelog body
runs:
  using: "node12"
  main: "dist/index.js"
