name: CI
on:
  push:
    tags:
      - v**
    branches:
      - main
      - release/**
    paths-ignore:
      - "README.md"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "README.md"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - run: npm ci
      - run: npm run build
      - run: npm run format-check
      - run: npm run test
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
      - uses: actions/upload-artifact@v4
        with:
          name: action.yml
          path: action.yml

  package:
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v'))
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "build: update distribution"
          title: Update distribution
          body: |
            - Updates the distribution for changes on `main`
            Auto-generated by [create-pull-request][1]
            [1]: https://github.com/peter-evans/create-pull-request
          branch: update-distribution
